global:
  # Настройки SMTP для отправки email
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@yourdomain.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

# Настройки маршрутизации
route:
  # Группировка алертов
  group_by: ['alertname', 'cluster', 'service']
  
  # Время группировки
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  
  # Получатель по умолчанию
  receiver: 'team-notifications'
  
  # Правила маршрутизации
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  
  - match:
      severity: warning
    receiver: 'warning-alerts'
    continue: true

# Получатели уведомлений
receivers:
- name: 'team-notifications'
  email_configs:
  - to: 'team@yourdomain.com'
    send_resolved: true
    headers:
      subject: '{{ template "email.subject" . }}'
    html: '{{ template "email.html" . }}'
  
  telegram_configs:
  - bot_token: 'YOUR_BOT_TOKEN'
    chat_id: 'YOUR_CHAT_ID'
    parse_mode: 'HTML'
    message: '{{ template "telegram.message" . }}'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@yourdomain.com'
    send_resolved: true
    headers:
      subject: '🚨 CRITICAL: {{ template "email.subject" . }}'
    html: '{{ template "email.critical" . }}'
  
  telegram_configs:
  - bot_token: 'YOUR_BOT_TOKEN'
    chat_id: 'ADMIN_CHAT_ID'
    parse_mode: 'HTML'
    message: '{{ template "telegram.critical" . }}'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'team@yourdomain.com'
    send_resolved: true
    headers:
      subject: '⚠️ WARNING: {{ template "email.subject" . }}'
    html: '{{ template "email.warning" . }}'
  
  telegram_configs:
  - bot_token: 'YOUR_BOT_TOKEN'
    chat_id: 'YOUR_CHAT_ID'
    parse_mode: 'HTML'
    message: '{{ template "telegram.warning" . }}'
    send_resolved: true

# Шаблоны для email
templates:
- '/etc/alertmanager/template/*.tmpl' 